### ISSUE TITLE
install errors on mac, ubuntu

### ISSUE THREAD

**Issue by pchalasani** [deepforge-dev/deepforge#1028]
is this ready for use ?

On Mac OSX, I did `sudo npm install -g deepforge`
```
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && node ./utils/postinstall.js -c jsdoc_conf.json
```

On Ubuntu I get similar errors

**Comment by brollb** [comment]
It looks like you installed nodejs directly (using apt-get/homebrew). Can you try installing nodejs using `nvm`? This way we can make sure the version is correct and you won't need to use `sudo` to install npm packages

**Comment by pchalasani** [comment]
I managed to get nodejs installed and also `npm install -g deepforge` works as well ( I made it install in my home dir, so I don't need `sudo`) on my Mac. But now I'm having problems with `deepforge start` -- some brew link errors (permission issues I think). Frankly quite tiresome overall.

**Comment by brollb** [comment]
I would try `npm install -g bower` and see if that fixes the original error. On ubuntu, are you using NodeJS from the official repos or installing from elsewhere? The official repos contain a rather old version of NodeJS (it looks like v4.x).

Also, I would strongly recommend that you use nvm rather than a modified homebrew installation. Debugging brew linking errors with a customized installation of nodejs using homebrew could be tricky and I suspect a bit more involved than just using `nvm`.

Otherwise, there are docker images for deepforge which would allow you to not have to worry about setting up a nodejs environment for the server. The instructions for starting deepforge using the docker images can be found in the [docs](http://deepforge.readthedocs.io/en/latest/deployment/native.html).

Sorry for the trouble but thanks for the feedback! I can look into this some more and see what I can do to make the installation process go more smoothly (including updating the docs to officially recommend using `nvm`).

**Comment by pchalasani** [comment]
Got it working finally on the mac -- used `nvm` as above, and had to run `deepforge start` a couple times, and finally it said it was running at `localhost:8888` and I go there in chrome and I see the UI. 

I already have RNN code in PyTorch, will this framework help me somehow keep track of my experiments and results, etc? (I guess I would need to install it on my AWS Ubuntu Deep Learning AMI, but wanted to know if it would be worth the trouble)

**Comment by brollb** [comment]
it currently doesn't support pytorch (uses torch7 and lua atm) but pytorch support is in the works (https://github.com/deepforge-dev/deepforge/issues/1024).

Of course, if you are using torch7 (in the future, pytorch), it should help manage experiments and results as they are available from the web ui as well as version controlled (both the code and the data) so past experiments are reproducible.
