### ISSUE TITLE
Add .gitattributes to ensure LF instead of CRLF

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1256]
This is pretty minor but would be good to have for new contributors (especially for anyone developing on windows).

**Comment by umesh-timalsina** [comment]
Since, some of the files are not modified and the `.gitattribute` settings causes a  freshly checkout repository to have changed files, because `eol=lf` attribute on paths which are in the index with `CRLF` line endings may make the paths to be considered dirty. So, they need to be recommitted to ensure that they have `LF` line endings.
Possible Fix:
1. Checkout master with `.gitattributes` file
2. See if some files with `CRLF` line-endings are changed.
3. Add the files from 2, commit the changes.
