### ISSUE TITLE
Allow changing of artifact type in ArtifactIndex

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1681]
Similar to `dblclick` handler for name change, we should be able to change the Artifact's type as well.

**Comment by brollb** [comment]
It would be nice if we could detect it automatically since it only makes sense to change it when it is unset. That is, it doesn't really make sense to change the value when it is set correctly as it will cause inconsistencies when that data is used in a pipeline. (A simple "echo" operation would update the type to the actual value and then a different serializer could be used.)

**Comment by brollb** [comment]
That said, this works in the meantime...

**Comment by umesh-timalsina** [comment]
This would be helpful if you decide to import an artifact first and implement a loader serialization module later.

**Comment by brollb** [comment]
> This would be helpful if you decide to import an artifact first and implement a loader serialization module later.

Why can't you? Maybe I don't understand correctly - you should be able to upload an artifact and then specify the serializer (as long as you specify the serializer before you use it in an operation).

I was referring to detect on import. The downside is that it could be quite slow to import if we need to run a small python job on something like SciServer (as submitting a job takes a little time). (It already is detected when it is the output of an operation.) Perhaps the bigger problem is the chick-and-egg problem that you get into when trying to check the type; if it needs a custom deserializer, then loading it will fail so you can't detect the type (and thus use the appropriate deserializer).

**Comment by umesh-timalsina** [comment]
>Why can't you? Maybe I don't understand correctly - you should be able to upload an artifact and then specify the serializer (as long as you specify the serializer before you use it in an operation).

Currently, an option to specify a Data Type while running `UploadArtifact` or `ImportArtifact` that I know of. But, I don't know a way to change the Data Type of an artifact when using it in an operation Input node or an Operation pointer. Is there a way to do that?

**Comment by brollb** [comment]
So, I am not convinced that we should change the data type as it doesn't actually change the data itself and is just a metadata field. 

Is there a case where there is more than one correct value for the data type field? Or where we would want to change it from a correct value to another value?

**Comment by umesh-timalsina** [comment]
> Is there a case where there is more than one correct value for the data type field? Or where we would want to change it from a correct value to another value?

I cannot think of one for the first case. For the second case, a type of `Unknown` could be changed to another type.

**Comment by brollb** [comment]
If the type information is missing (I believe that is what you mean by `Unknown`, right?), it certainly makes sense to be able to add it. However, that isn't really what I was asking in the second question since I don't consider a missing field to have the correct value. Does that make sense?

For now, I think this will be fine to add because we aren't validating the type information so we cannot ensure that it is correct. As we don't know that it is correct, it may be appropriate for the user to modify it. My concern is that this could be abused to insert invalid values for artifacts and be a bit confusing for users as this could cause deserialization errors.

Perhaps it would be worthwhile to validate the types for uploaded/imported artifacts... Unfortunately, this could be slow and would make the process of uploading data more cumbersome...

**Comment by umesh-timalsina** [comment]
>If the type information is missing (I believe that is what you mean by Unknown, right?), it certainly makes sense to be able to add it. However, that isn't really a compelling answer to the second question since I don't consider a missing field to have the correct value. Does that make sense?

Yeah, it makes sense.  However, there could be some value in changing the artifact `type` instead of uploading/importing it again. 

> For now, I think this will be fine to add because we aren't validating the type information so we cannot ensure that it is correct. As we don't know that it is correct, it may be appropriate for the user to modify it. My concern is that this could be abused to insert invalid values for artifacts and be a bit confusing for users as this could cause deserialization errors.

We could use a Dialog/Prompt warning that this could lead to deserialization errors. Or even better, if we could validate that in some way, either my checking whether the changed value is available and registered as a serialization module that would be nice as well.  

The other route we could take is only allow this change to happen once i.e. In other words, you could switch from to default serializer to the custom one but that's not logical, as that kind of defies the `metamodel` IMO.

> Perhaps it would be worthwhile to validate the types for uploaded/imported artifacts... Unfortunately, this could be slow and would make the process of uploading data more cumbersome...

It might be worthwhile to have a separate plugin for validation and we run it before the job is executed. I would be curious to know your suggestions to make it little more efficient / less cumbersom.
