### ISSUE TITLE
Refactor Storage integration test to use a single function

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1718]
Instead of using several test cases, a single function with the following steps should be used to test different storage backends

1. Create a buffer from existing content
2. Put the buffer as a file in the backend client
3. Get the file and verify content
3. Stat the file and verify `dataInfo`.
4. Delete the file in storage.

**Comment by umesh-timalsina** [comment]
Also extend #1703 with the test

**Comment by brollb** [comment]
I am not sure if I understand the motivation here. What is wrong with multiple fine-grained tests?

**Comment by umesh-timalsina** [comment]
Basically, I don't like how these test cases have a shared variable(`dataInfo`). So, it makes sense consolidate the storage features testsm into a single function.

**Comment by brollb** [comment]
Yeah, I am still torn. Both versions have issues. The tests in the current version are not independent; if the `getFile` test fails, then the subsequent tests will also fail. The proposed change will remove the dependence between tests by simply making them a single test. The problem with the proposed fix is that it doesn't actually remove any of the dependence of the functionality that is tested - it simply combines them into a single test so it appears to be one test.

Basically, the best practice is to have granular, independent tests that test only one thing. The current tests are not independent whereas the proposed change makes them test all the functionality at once.

I have no problem making the change if there is a compelling case for it. However, I am concerned because it seems to me the best course of action to improve the current version would be to try to remove the dependence between tests rather than combining them into a single test.

**Comment by umesh-timalsina** [comment]
I am closing this and the PR. Close #1719.
