### ISSUE TITLE
Switching backends in matplotlib 3.3.0 fails

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1792]
With exporting custom backend in matplotlib 3.3.0
```sh
src/plugins/GenerateJob/templates$  export MPLBACKEND=module://backend_deepforge
```

```py

Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.__version__
'3.3.0'
>>> from matplotlib import pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/umesh/anaconda3/envs/deepforge/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2319, in <module>
    switch_backend(rcParams["backend"])
  File "/home/umesh/anaconda3/envs/deepforge/lib/python3.7/site-packages/matplotlib/pyplot.py", line 283, in switch_backend
    matplotlib.backends.backend = newbackend
AttributeError: module 'matplotlib' has no attribute 'backends'
>>> 
```

When used with a pipeline execution:
![image](https://user-images.githubusercontent.com/11476842/88133188-132e4d80-cba7-11ea-89ef-082756a11a0e.png)

**Comment by umesh-timalsina** [comment]
For now we should pin `matplotlib==3.2.2`, which will be helpful in resolving https://github.com/deepforge-dev/deepforge/pull/1747#issuecomment-661971862 as well.

**Comment by brollb** [comment]
Pinning matplotlib to 3.2.2 is a good idea.

It looks like the bug is actually in matplotlib - our code is simply importing `pyplot` and it is failing. (It's hard to argue that the error is on our side when we aren't able to get past the import!) It might be worth seeing if anyone else has encountered this issue on the latest version of matplotlib but I wouldn't put it as a high priority since 3.2.2 should work just fine for now.
